name: CI/CD Pipeline with Testing and Docker

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Run tests with pytest
        run: |
          pytest app/test_app.py --maxfail=1 --disable-warnings

      - name: Stop if tests fail
        if: failure()
        run: |
          echo "Tests failed, stopping the process."

      - name: Build Docker image
        if: success()
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-devops-demo:latest .

      - name: Test Docker image
        if: success()
        run: |
          docker run --rm -d -p 5000:5000 --name test_container ${{ secrets.DOCKER_USERNAME }}/my-devops-demo:latest
          sleep 5
          curl -f http://localhost:5000 || exit 1
          docker stop test_container

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        if: success()
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-devops-demo:latest
